---
# TODO: replace unneeded sudo and sudo_user attributes with user and group
# permissions
# TODO: break into smaller tasks - such as configuring all X stuff with a
# single command.

#- name: Upgrade the system
#  apt: upgrade=dist

- name: Install the debs
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - libncursesw5-dev
    - zlib1g-dev
    - python-dev
    - cmake

# Setup atom (https://atom.io/) ppa and install.
- name: Add custom Galaxy PPA (used for atom package)
  apt_repository: repo="ppa:webupd8team/atom" update_cache=yes
  when: galaxy_devbox_include_x

# Setup komodo-edit ppa and install.
- name: Add custom PPA (used for komodo-edit package)
  apt_repository: repo="ppa:mystic-mirage/komodo-edit" update_cache=yes
  when: galaxy_devbox_include_x

- name: Install the debs (X11 environment)
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - atom
    - komodo-edit
    - xfce4-xkb-plugin
    - gedit
    - xubuntu-core
    - firefox
  when: galaxy_devbox_include_x

- name: Add Google key for Chrome installation
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  when: galaxy_devbox_include_x

- name: Add Google APT repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
  when: galaxy_devbox_include_x

- name: Install Chrome Stable
  apt:
    name: google-chrome-stable
    state: latest
  when: galaxy_devbox_include_x

- name: Ensures /etc/lightdm/lightdm.conf.d/ dir exists
  file: path=/etc/lightdm/lightdm.conf.d/ state=directory

- name: Configure GUI to auto login the dev user.
  template: src=10-xubuntu.conf.j2 dest=/etc/lightdm/lightdm.conf.d/10-xubuntu.conf
  when: galaxy_devbox_include_x

- name: Install linuxbrew
  become: True
  become_user: "{{ dev_user_name }}"
  shell: "ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)\""

- name: Install vim extras
  become: True
  become_user: "{{ dev_user_name }}"
  shell: "curl http://j.mp/spf13-vim3 -L -o - | sh"

- name: Tap galaxyproject recipes
  become: True
  become_user: "{{ dev_user_name }}"
  shell: "{{ dev_user_home }}//.linuxbrew/bin/brew tap galaxyproject/tap"

- name: Install planemo
  become: True
  become_user: "{{ dev_user_name }}"
  shell: "{{ dev_user_home }}/.linuxbrew/bin/brew install -v planemo"

- name: Setup .planemo.yml
  template: src=planemo.yml.j2 dest={{ dev_user_home }}/.planemo.yml owner={{ dev_user_name }} group={{ dev_user_group }}

- name: Configure Destop directory.
  file: path={{ dev_user_home }}/Desktop state=directory  owner={{ dev_user_name }} group={{ dev_user_group }}
  when: galaxy_devbox_include_x

- name: Configure Destop shortcuts.
  template: src=Desktop/{{ item }}.desktop.j2 dest={{ dev_user_home }}/Desktop/{{ item }}.desktop mode=a+x owner={{ dev_user_name }} group={{ dev_user_group }}
  when: galaxy_devbox_include_x
  with_items:
    - atom
    - komodo-edit
    - exo-terminal-emulator
    - exo-web-browser
    - galaxyproject
    - ipython
    - localgalaxy
    - localtoolshed
    - planemo
    - toolsyntax

- name: Configure Desktop link to development tools.
  file: src={{ dev_tool_conf_dir }} dest={{ dev_user_home }}/Desktop/tools state=link owner={{ dev_user_name }} group={{ dev_user_group }} force=true
  when: galaxy_devbox_include_x

- name: Install linuxbrew bash completion stuff
  become: True
  become_user: "{{ dev_user_name }}"
  shell: "{{ dev_user_home }}/.linuxbrew/bin/brew install -v bash-completion"

# TODO: MANPATH, INFOPATH
- name: Add linuxbrew to dev users PATH
  lineinfile: "dest={{ dev_user_shellrc }} line='export PATH={{ dev_user_home }}/.linuxbrew/bin:$PATH'"

- name: Source linuxbrew bash completions
  lineinfile: "dest={{ dev_user_shellrc }} line='. {{ dev_user_home }}/.linuxbrew/etc/bash_completion'"

- name: Install the dev tools
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - emacs24-nox

- name: Install node and npm
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nodejs
    - npm

- name: Link nodejs to node
  become: True
  shell: "ln -f -s /usr/bin/nodejs /usr/bin/node"

- name: Install more locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - en_GB.UTF-8
    - de_DE.UTF-8


- name: Add dev tool configuration file.
  template: src=dev_tool_conf.xml.j2 dest={{ dev_tool_conf }}

- name: Add planemo machine web content
  git: repo={{ planemo_machine_web_repo }} dest={{ planemo_machine_web_dir }} accept_hostkey=yes
  when: nginx_serve_planemo_machine_web

- name: Add small tool conf
  template: src=tool_conf.small.xml.j2 dest={{ small_tool_conf_path }}
  when: small_tool_conf

- name: "Install Galaxy management scripts."
  template: src=restart_galaxy.j2 dest=/usr/local/bin/restart_galaxy mode=a+x